server:
  bind:
    host: localhost #change to your hostname if running your own instance
    port: 5005
  url: ${PYGEOAPI_URL:-http://localhost:5005} #change to host URL  if running your own instance
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: true
  language: en-US
  cors: true
  pretty_print: true
  templates:
    path: /opt/pygeoapi/pygeoapi-deployment/templates
  limits:
    default_items: 500
    max_items: 10000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'

logging:
  level: ${PYGEOAPI_LOGLEVEL:-ERROR}
  # logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title: Western Water Datahub
    description: The Western Water Datahub is an implementation of OGC API - EDR supported by the United States Bureau of Reclamation.
    keywords:
      - usbr
      - wwdh
      - iow
    keywords_type: theme
    terms_of_service: https://opensource.org/license/MIT
    url: https://github.com/internetofwater/WWDH
  license:
    name: MIT License
    url: https://opensource.org/license/MIT
  provider:
    name: Internet of Water
    url: https://github.com/internetofwater/WWDH
  contact:
    address: 113 Brattle St
    city: Cambridge
    stateorprovince: Massachussetts
    postalcode: 02138
    country: USA
    email: bwebb@lincolninst.edu
    url: https://cgsearth.org
    role: pointOfContact
    name: Benjamin Webb

resources:
  lakes:
    type: collection
    title:
      en: Large Lakes
      fr: Grands Lacs
    description:
      en: lakes of the world, public domain
      fr: lacs du monde, domaine public
    keywords:
      en:
        - lakes
        - water bodies
      fr:
        - lacs
        - plans d'eau
    links:
      - type: text/html
        rel: canonical
        title: information
        href: http://www.naturalearthdata.com/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: 2011-11-11T11:11:11Z
        end: null # or empty (either means open ended)
    providers:
      - type: feature
        name: GeoJSON
        data: tests/data/ne_110m_lakes.geojson
        id_field: id
        title_field: name
