server:
  bind:
    host: localhost #change to your hostname if running your own instance
    port: 5005
  url: ${PYGEOAPI_URL:-http://localhost:5005} #change to host URL  if running your own instance
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: true
  language: en-US
  cors: true
  pretty_print: true
  templates:
    path: /opt/pygeoapi/pygeoapi-deployment/templates
  limits:
    default_items: 500
    max_items: 10000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'

logging:
  level: ${PYGEOAPI_LOGLEVEL:-ERROR}
  # logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title: Western Water Datahub
    description: The Western Water Datahub is an implementation of OGC API - EDR supported by the United States Bureau of Reclamation.
    keywords:
      - usbr
      - wwdh
      - iow
    keywords_type: theme
    terms_of_service: https://opensource.org/license/MIT
    url: https://github.com/internetofwater/WWDH
  license:
    name: MIT License
    url: https://opensource.org/license/MIT
  provider:
    name: Internet of Water
    url: https://github.com/internetofwater/WWDH
  contact:
    address: 113 Brattle St
    city: Cambridge
    stateorprovince: Massachussetts
    postalcode: 02138
    country: USA
    email: bwebb@lincolninst.edu
    url: https://cgsearth.org
    role: pointOfContact
    name: Benjamin Webb

resources:

  ADWR_GWSI_Sites:
    type: collection
    title: Arizona Department of Water Resources Groundwater Storage Index
    description: Sites of the Arizona Department of Water Resources Groundwater Storage Index
    keywords: ["sites"]
    links:
      - type: application/html
        rel: canonical
        title: data source
        hreflang: en-U
        href: https://services.arcgis.com/C34zQ7veRS0V1t04/ArcGIS/rest/services/GWSI_Layers/FeatureServer/7
    extents: 
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
        - data: https://services.arcgis.com/C34zQ7veRS0V1t04/ArcGIS/rest/services/GWSI_Layers/FeatureServer/7
          type: feature
          name: ESRI
          id_field: OBJECTID
          time_field: LASTWLDATE

  usace-edr:
    type: collection
    title: US Army Corps of Engineers
    description: USACE Access2Water API
    extents: 
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    keywords:
      - open data
    providers:
      - &default-edr
        type: edr
        name: usace.usace_edr.USACEEDRProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
      - &default-feature
        type: feature
        name: usace.usace.USACEProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
        entity: Observation
        title_field: name

  snotel-edr:
    type: collection
    title: Snow Telemetry Network
    description: USDA Snow Telemetry Network (SNOTEL) EDR
    keywords:
      - EDR
      - SNOTEL
      - NRCS
      - USDA
    links:
      - &default-link
        type: application/html
        rel: canonical
        title: data source
        href: https://www.nrcs.usda.gov/wps/portal/wcc/home/aboutUs/monitoringPrograms/automatedSnowMonitoring/
        hreflang: en-US
    extents:
      spatial:
        bbox: [-164.92472, 32.92342, -103.78758, 70.28062]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - <<: *default-edr
        name: snotel.snotel_edr.SnotelEDRProvider
        data: https://wcc.sc.egov.usda.gov/
      - <<: *default-feature
        name: snotel.snotel.SnotelProvider
        data: https://wcc.sc.egov.usda.gov/

  usgs-sta:
    type: collection
    title: United States Geologic Survey Streamgages
    description: USGS Streamgages SensorThings API EDR
    keywords:
      - EDR
      - SensorThings
      - USGS
    links:
      - <<: *default-link
        href: https://labs.waterdata.usgs.gov
    extents: &default-extent
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: edr
        name: SensorThingsEDR
        data: https://labs.waterdata.usgs.gov/sta/v1.1/
      - type: feature
        name: SensorThings
        data: https://labs.waterdata.usgs.gov/sta/v1.1/
        entity: Things
        title_field: name

  awdb-forecasts-edr:
    type: collection
    title: Air and Water Database Forecasts
    description: USDA Air and Water Database Forecasts (AWDB) EDR
    keywords:
      - open data
    extents: *default-extent
    providers:
      - type: edr
        name: awdb_forecasts.awdb_forecasts_edr.AwdbForecastsEDRProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
      - type: feature
        name: awdb_forecasts.awdb_forecasts.AwdbForecastsProvider
        data: https://wcc.sc.egov.usda.gov/awdbRestApi/v3/api-docs
        title_field: name
