# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: MIT

name: Pyright Type Checks

on:
  push:
  workflow_dispatch:

jobs:
  pyright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run checks in Nix shell
        run: |
          nix develop --extra-experimental-features "nix-command flakes" \
            github:NixOS/nixpkgs/nixpkgs-unstable \
            --command bash -c '
              nix-env -iA nixpkgs.gdal_3_10 nixpkgs.python311 nixpkgs.nodejs nixpkgs.uv

              uv sync --all-extras --dev --all-packages --all-groups
              uv run pyright
            '